default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_back_end_development
  user: postgres
  password: password
  
test:
  <<: *default
  database: hello_rails_back_end_test
  user: postgres
  password: password

production:
  <<: *default
  database: hello_rails_back_end_production
  username: hello_rails_back_end
  password: <%= ENV["HELLO_RAILS_BACK_END_DATABASE_PASSWORD"] %>
